# spell-checker:ignore logind

[package]
name = "sg_users"
description = "users ~ (uutils) display names of currently logged-in users"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[features]
feat_systemd_logind = ["sgcore/feat_systemd_logind"]

[lib]
path = "src/users.rs"

[dependencies]
clap = { workspace = true }
sgcore = { workspace = true, features = ["utmpx"] }
fluent = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "openbsd")'.dependencies]
utmp-classic = { workspace = true }

[target.'cfg(target_os = "openbsd")'.dependencies]
pledge = "0.4"

[[bin]]
name = "users"
path = "src/main.rs"
