[package]
name = "sg_unexpand"
description = "unexpand ~ (uutils) convert input spaces to tabs"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/unexpand.rs"

[dependencies]
thiserror = { workspace = true }
clap = { workspace = true }
unicode-width = { workspace = true }
sgcore = { workspace = true }
fluent = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
tempfile = { workspace = true }
sgcore = { workspace = true, features = ["benchmark"] }

[target.'cfg(target_os = "openbsd")'.dependencies]
pledge = "0.4"

[[bin]]
name = "unexpand"
path = "src/main.rs"

[[bench]]
name = "unexpand_bench"
harness = false
