# spell-checker:ignore logind


[package]
name = "sg_who"
description = "who ~ (uutils) display information about currently logged-in users"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/who"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[features]
feat_systemd_logind = ["sgcore/feat_systemd_logind"]

[lib]
path = "src/who.rs"

[dependencies]
clap = { workspace = true }
sgcore = { workspace = true, features = ["utmpx"] }
fluent = { workspace = true }

[[bin]]
name = "who"
path = "src/main.rs"
