# spell-checker:ignore datetime tzdb zoneinfo
[package]
name = "sg_get_date"
description = "get-date ~ (stargate) display or set the current time"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/get_date.rs"

[dependencies]
clap = { workspace = true }
fluent = { workspace = true }
jiff = { workspace = true, features = [
  "tzdb-bundle-platform",
  "tzdb-zoneinfo",
  "tzdb-concatenated",
] }
parse_datetime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sgcore = { workspace = true, features = ["parser"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "openbsd")'.dependencies]
pledge = "0.4"

[[bin]]
name = "get-date"
path = "src/main.rs"
