[package]
name = "sg_scan_bt"
version = "0.4.0"
authors = ["Dmitry Kalashnikov"]
license = "MIT"
edition = "2021"

[[bin]]
name = "scan-bt"
path = "main.rs"

[dependencies]
clap = { workspace = true }
sgcore = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = "1.19.0"

[target.'cfg(target_os = "linux")'.dependencies]
btleplug = "0.11"
tokio = { version = "1", features = ["rt", "macros", "time"] }
