[package]
name = "sg_csplit"
description = "csplit ~ (uutils) Output pieces of FILE separated by PATTERN(s) to files 'xx00', 'xx01', ..., and output byte counts of each piece to standard output"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/csplit.rs"

[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }
sgcore = { workspace = true, features = ["entries", "fs", "format"] }
fluent = { workspace = true }

[target.'cfg(target_os = "openbsd")'.dependencies]
pledge = "0.4"

[[bin]]
name = "csplit"
path = "src/main.rs"
