[package]
name = "sg_dd"
description = "dd ~ (stargate) copy and convert files"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/dd.rs"

[dependencies]
clap = { workspace = true }
gcd = { workspace = true }
libc = { workspace = true }
sgcore = { workspace = true, features = [
  "format",
  "parser",
  "quoting-style",
  "fs",
] }
thiserror = { workspace = true }
fluent = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
signal-hook = { workspace = true }
nix = { workspace = true, features = ["fs"] }

[[bin]]
name = "dd"
path = "src/main.rs"
