[package]
name = "sg_yes"
description = "yes ~ (uutils) repeatedly display a line with STRING (or 'y')"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/yes.rs"

[dependencies]
clap = { workspace = true }
itertools = { workspace = true }
fluent = { workspace = true }

[target.'cfg(unix)'.dependencies]
sgcore = { workspace = true, features = ["pipes", "signals"] }
nix = { workspace = true }

[target.'cfg(not(unix))'.dependencies]
sgcore = { workspace = true, features = ["pipes"] }

[target.'cfg(target_os = "openbsd")'.dependencies]
pledge = "0.4"

[[bin]]
name = "yes"
path = "src/main.rs"
