[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-apple-darwin]
rustflags = ["-L", "/usr/local/lib", "-C", "link-arg=-Wl,-rpath,/usr/local/lib"]

[target.aarch64-apple-darwin]
rustflags = ["-L", "/usr/local/lib", "-C", "link-arg=-Wl,-rpath,/usr/local/lib"]
