[package]
name = "sg_cp"
description = "cp ~ (stargate) copy SOURCE to DESTINATION"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/cp.rs"

[dependencies]
clap = { workspace = true }
filetime = { workspace = true }
libc = { workspace = true }
linux-raw-sys = { workspace = true, features = ["ioctl"] }

sgcore = { workspace = true, features = [
  "backup-control",
  "buf-copy",
  "entries",
  "fs",
  "fsxattr",
  "parser",
  "perms",
  "mode",
  "update-control",
] }
walkdir = { workspace = true }
indicatif = { workspace = true }
thiserror = { workspace = true }
fluent = { workspace = true }

[target.'cfg(unix)'.dependencies]
xattr = { workspace = true }
exacl = { workspace = true, optional = true }

[[bin]]
name = "cp"
path = "src/main.rs"

[dev-dependencies]
divan = { workspace = true }
tempfile = { workspace = true }
sgcore = { workspace = true, features = ["benchmark"] }

[[bench]]
name = "cp_bench"
harness = false