[package]
name = "sg_mktemp"
description = "mktemp ~ (stargate) create and display a temporary file or directory from TEMPLATE"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/mktemp.rs"

[dependencies]
clap = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
sgcore = { workspace = true }
fluent = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "mktemp"
path = "src/main.rs"
