[package]
name = "sg_cksum"
description = "cksum ~ (stargate) display CRC and size of input"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/cksum.rs"

[dependencies]
clap = { workspace = true }
sgcore = { workspace = true, features = ["checksum", "encoding", "sum"] }
hex = { workspace = true }
fluent = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
tempfile = { workspace = true }
sgcore = { workspace = true, features = ["benchmark"] }

[[bin]]
name = "cksum"
path = "src/main.rs"

[[bench]]
name = "cksum_bench"
harness = false
