[package]
name = "sg_realpath"
description = "realpath ~ (stargate) display resolved absolute path of PATHNAME"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/realpath.rs"

[dependencies]
clap = { workspace = true }
sgcore = { workspace = true, features = ["fs"] }
fluent = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "realpath"
path = "src/main.rs"
