# spell-checker:ignore bigdecimal extendedbigdecimal
[package]
name = "sg_get_range"
description = "get-range ~ (stargate) display a sequence of numbers"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/get_range.rs"

[dependencies]
bigdecimal = { workspace = true }
clap = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
sgcore = { workspace = true, features = [
  "extendedbigdecimal",
  "fast-inc",
  "format",
  "parser",
  "quoting-style",
] }
fluent = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "get-range"
path = "src/main.rs"

[dev-dependencies]
divan = { workspace = true }
tempfile = { workspace = true }
sgcore = { workspace = true, features = ["benchmark"] }

[[bench]]
name = "seq_bench"
harness = false
