[package]
name = "sg_rmdir"
description = "rmdir ~ (stargate) remove empty DIRECTORY"
repository = "https://github.com/klimb/rust-stargate"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/rmdir.rs"

[dependencies]
clap = { workspace = true }
sgcore = { workspace = true, features = ["fs"] }
libc = { workspace = true }
fluent = { workspace = true }

[[bin]]
name = "rmdir"
path = "src/main.rs"
